spring:
  security:
    jwt:
      key: zxcvbnm
      expire: 7

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 2713613951
    driver-class-name: com.mysql.cj.jdbc.Driver
